# ─── techtra-shop/Dockerfile ──────────────────────────────────────────────────

FROM nginx:alpine
COPY . /usr/share/nginx/html
COPY nginx.shop.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
